name: Build and Push to AWS ECR


# on:
#   push:
#     branches:
#       - main


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Get timestamp for unique tag
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"

    - name: Build and tag Docker image with timestamp
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest -t ${{ secrets.ECR_REPOSITORY_URI }}:${{ steps.timestamp.outputs.timestamp }} .

    - name: Push Docker images to Amazon ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ steps.timestamp.outputs.timestamp }}
        echo "Image pushed with tags: latest and ${{ steps.timestamp.outputs.timestamp }}"

    - name: Update ECS service
      run: |
        aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER }} --service ${{ secrets.ECS_SERVICE }} --force-new-deployment
      continue-on-error: false
